name: Flake8 Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifie le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v2

      # Étape 2 : Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  

      # Étape 3 : Installation de Flake8
      - name: Install Flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # Étape 4 : Lance Flake8 pour vérification
      - name: Run Flake8 for linting
        run: flake8 .
